apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbachhav-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sbachhav-springboot
  template:
    metadata:
      labels:
        app: sbachhav-springboot
    spec:
      containers:
        - name: springboot
          image: sunitabachhav2007/sbachhav-docker-demo:sbachhav-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sbachhav-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sbachhav-springboot
